Repository importPI19fromDHGE/dhge-pi19-sem5, pull requests merged in 2021-09, with the labels that each got.

#1 Erste Module
  .gitignore
  ABWL-LEDER/README.md
  EMB-GUENTHER/README.md
  GDV-HERBST/README.md
  NET-BARIE/README.md
  PLD-BARIE/README.md
  README.md
  RES-GUENTHER/README.md
  SEW-KUSCHE/README.md
  WEB-MUELLER/README.md
Labels: documentation

#2 Linter, TOC, Pandoc und Anki Action
  .github/workflows/anki.yml
  .github/workflows/lint.yml
  .github/workflows/pandoc.yml
  .github/workflows/toc.yml
  .gitignore
  .mdl.rb
  .mdlrc
Labels: enhancement

#3 README Anki Hinweis
  ABWL-LEDER/README.md
  EMB-GUENTHER/README.md
  GDV-HERBST/README.md
  NET-BARIE/README.md
  PLD-BARIE/README.md
  README.md
  RES-GUENTHER/README.md
  SEW-KUSCHE/README.md
  WEB-MUELLER/README.md
Labels: documentation

#4 ABWL Vorlesung 07.09.2021
  ABWL-LEDER/README.md
Labels: documentation

#9 E-Commerce Ergänzungen 08.09.2021
  .mdl.rb
  WEB-MUELLER/README.md
Labels: documentation

#15 EMB Ergänzungen vom 13.09.2021
  EMB-GUENTHER/README.md
Labels: documentation, multi-pr

#14 Embedded II 13.09.2021
  EMB-GUENTHER/README.md
Labels: documentation

#12 Software-Entwicklungswerkzeuge 13.09.2021
  SEW-KUSCHE/README.md
Labels: documentation

#22 Softwareentwicklungswerkzeuge 15.09.2021
  .mdl.rb
  SEW-KUSCHE/README.md
Labels: documentation

#21 EMB vom 15.09.2021
  EMB-GUENTHER/README.md
Labels: documentation

#23 SEW vom 16.09.2021
  SEW-KUSCHE/README.md
Labels: documentation

#27 Linterfix für Oliver
  ABWL-LEDER/README.md
Labels: bug, documentation

#24 ABWL 210917 + vscode-markdownlint settings
  .gitignore
  .vscode/settings.json
  ABWL-LEDER/README.md
  ABWL-LEDER/assets/fmea.png
Labels: documentation

#29 Markdown-Linter Doku
  README.md
Labels: documentation

#28 fix `pandoc` silently failing
  .github/workflows/pandoc.yml
Labels: bug

#31 Fix `too deeply nested`
  .github/workflows/pandoc.yml
  NET-BARIE/README.md
  enumitem.sty
Labels: bug

#32 EMB vom 22.09.2021
  EMB-GUENTHER/README.md
Labels: documentation

#33 E-Commerce 23.09.2021
  WEB-MUELLER/README.md
Labels: documentation

#34 WEB 2021.09.24
  WEB-GRIMM/README.md
Labels: documentation

#35 Webanwendungen vom 23.09.2021
  WEB-GRIMM/README.md
Labels: documentation

#36 Theorie vom 27.09.2021
  SEW-KUSCHE/README.md
Labels: documentation
