Repository importPI19fromDHGE/dhge-pi19-sem5, pull requests merged in 2021-11, with the labels that each got.

#62 Klausur Ergänzung
  ABWL-LEDER/README.md
Labels: documentation

#70 Fix ``too deeply nested`` once again
  RES-GUENTHER/README.md
Labels: documentation

#69 Lernsession 1
  GDV-HERBST/appendix/LKF.md
Labels: documentation

#73 vergessene PR
  RES-GUENTHER/README.md
Labels: documentation

#77 fix trailing whitespaces for LKF Skript 3 PR
  ABWL-LEDER/appendix/LKF.md
Labels: documentation

#68 [GH Action] create anki decks for LKF
  .github/workflows/anki.yml
Labels: help wanted

#79 fancy input - Web 10.11.2021
  WEB-GRIMM/README.md
  WEB-GRIMM/extra/fancy-input/fancy_js.js
  WEB-GRIMM/extra/fancy-input/fancy_style.css
  WEB-GRIMM/extra/fancy-input/schickes_input.html
Labels: documentation

#85 format pld tables
  PLD-BARIE/README.md
Labels: documentation

#80 RES: pipe-01 und pipe-02
  RES-GUENTHER/extra/pipe/pipe-01.c
  RES-GUENTHER/extra/pipe/pipe-02_two_pipes.c
  RES-GUENTHER/extra/pipe/pipe-02_with_semaphores.c
Labels: documentation

#81 ABWL LKF vom 11.11.2021
  ABWL-LEDER/appendix/LKF.md
Labels: documentation

#82 ein paar Projektmanagement LKF
  ABWL-LEDER/appendix/LKF.md
Labels: documentation

#83 WEB vom [viele Termine]
  WEB-GRIMM/README.md
Labels: documentation

#88 SEW LKF
  SEW-KUSCHE/appendix/ZSM.md
Labels: documentation

#89 socket-01-unix.c Kommentierung
  RES-GUENTHER/extra/socket/socket-01-unix.c
Labels: documentation

#92 socket inet comments
  RES-GUENTHER/extra/socket/socket-01-inet.c
Labels: documentation

#94 WEB vom 16.11.2021
  WEB-GRIMM/README.md
Labels: documentation

#97 WEB Cheatsheet vom 16.11.2021
  WEB-GRIMM/appendix/assets/box_model.png
  WEB-GRIMM/appendix/cheatsheet.md
Labels: documentation

#90 RES - 15/11/21
  RES-GUENTHER/README.md
Labels: documentation

#99 Web-Cheatsheet: JS
  WEB-GRIMM/appendix/cheatsheet.md
Labels: documentation

#102 Yet another WEB cheatsheet
  WEB-GRIMM/extra/cheatsheet-ybe.pdf
Labels: documentation

#91 GDV - neue LKF
  GDV-HERBST/appendix/LKF.md
Labels: documentation

#105 Socket chat (socket-04) aber in rust!
  RES-GUENTHER/extra/socket/chat-rust/.gitignore
  RES-GUENTHER/extra/socket/chat-rust/Cargo.toml
  RES-GUENTHER/extra/socket/chat-rust/src/main.rs
Labels: documentation

#101 ABWL LKF Ergänzungen
  ABWL-LEDER/README.md
  ABWL-LEDER/appendix/LKF.md
Labels: documentation, help wanted

#107 Rename NET-Barie heading
  NET-BARIE/README.md
Labels: bug

#109 GDV - Glossar
  GDV-HERBST/appendix/Glossar.md
  GDV-HERBST/appendix/assets/additive.png
  GDV-HERBST/appendix/assets/objektraum.png
  GDV-HERBST/appendix/assets/plm.png
  GDV-HERBST/appendix/assets/produktentwicklung.png
  GDV-HERBST/appendix/assets/rasterung.png
  GDV-HERBST/appendix/assets/virtuellesprodukt.png
Labels: documentation

#110 GDV LKF Update von Teamssitzung
  GDV-HERBST/appendix/LKF.md
  GDV-HERBST/appendix/assets/grafikpipeline.png
Labels: documentation

#112 Update Glossar
  GDV-HERBST/appendix/Glossar.md
Labels: documentation

#108 GDV-LKF-Jonathan-221
  GDV-HERBST/appendix/Klausur.md
  GDV-HERBST/appendix/LKF.md
  GDV-HERBST/extra/checklist.md
Labels: documentation

#113 GDV Glossar
  GDV-HERBST/appendix/Glossar.md
  GDV-HERBST/appendix/assets/aufbau-cad-dcc.png
  GDV-HERBST/appendix/assets/grafikpipeline-2d.png
  GDV-HERBST/appendix/assets/grafikpipeline-3d.png
  GDV-HERBST/appendix/assets/plm-konstruktion.png
  GDV-HERBST/appendix/assets/pps.png
  GDV-HERBST/appendix/assets/prozesskette.png
Labels: documentation

#119 GDV-Glossar: Typos und Ergänzungen
  GDV-HERBST/appendix/Glossar.md
Labels: documentation

#121 GDV LKF vom 24.11.2021
  GDV-HERBST/appendix/LKF.md
Labels: documentation

#123 LKF - TODOs abarbeiten
  GDV-HERBST/appendix/LKF.md
Labels: bug, documentation
